export const data = [
    {   id: 111,
        company: 'Gainsight',
        title: 'front-end developer',
        time: 'May 2020 - August 2021',
        list: [
            'Worked with React props, state, keys, refs, events, default props, and propTypes.',
            'Experience with Redux for state management. Created store, actions, and reducers as pure functions.',
            'Experience with Redux middleware’s - react-video, react-select, react-tagsinput, react-datagrid, react-panels, react-calendar.',
            'Experience with third-party React components library like react-grid, react-sortable, react-tags, react-infinite-scroll, react-date picker, and react-tagsinput, react-select, react-video.',
            'Extensive experience with Promises to make asynchronous calls and use fetch API as an interface to fetch resources.',
            'Experience with JavaScript (ES5/ES6/ES7) - Closures, Hoisting, Strict Mode, Scope, Block Scoping, Promises, Generators, Maps and Sets, String interpolation, async and await, array Extensions, modules, and classes.',
            'Built out Restful endpoints and lightweight aggregation layers using NodeJs frameworks such as Express, Body parser, cluster, process, Winston, Redis, passport, mongoose, lodash, etc.',
            'Used Mongoose Schema/Model to create, update and delete with Express controllers.',
            'Created Restful APIs with Express and used MongoDB for persistence and Redis for caching.',
            'Created SPA (Single Page Application) by configuring React-Router. Used Browser Router for Web.',
        ]
    },
    {   id: 222,
        company: 'Aspect',
        title: 'front-end developer',
        time: 'Dec 2018 to Apr 2020',
        list: [
            'Worked with React props, state, keys, refs, events, default props, and propTypes.',
            'Experience with Redux for state management. Created store, actions, and reducers as pure functions.',
            'Experience with Redux middleware’s - react-video, react-select, react-tagsinput, react-datagrid, react-panels, react-calendar.',
            'Experience with third-party React components library like react-grid, react-sortable, react-tags, react-infinite-scroll, react-date picker, and react-tagsinput, react-select, react-video.',
            'Extensive experience with Promises to make asynchronous calls and use fetch API as an interface to fetch resources.',
            'Experience with JavaScript (ES5/ES6/ES7) - Closures, Hoisting, Strict Mode, Scope, Block Scoping, Promises, Generators, Maps and Sets, String interpolation, async and await, array Extensions, modules, and classes.',
            'Built out Restful endpoints and lightweight aggregation layers using NodeJs frameworks such as Express, Body parser, cluster, process, Winston, Redis, passport, mongoose, lodash, etc.',
            'Used Mongoose Schema/Model to create, update and delete with Express controllers.',
            'Created Restful APIs with Express and used MongoDB for persistence and Redis for caching.',
            'Created SPA (Single Page Application) by configuring React-Router. Used Browser Router for Web.',
        ]
    },
    {   id: 333,
        company: 'Skytouch',
        title: 'front-end developer',
        time: 'Nov 2016 - Oct 2018',
        list: [
            'Worked with React props, state, keys, refs, events, default props, and propTypes.',
            'Experience with Redux for state management. Created store, actions, and reducers as pure functions.',
            'Experience with Redux middleware’s - react-video, react-select, react-tagsinput, react-datagrid, react-panels, react-calendar.',
            'Experience with third-party React components library like react-grid, react-sortable, react-tags, react-infinite-scroll, react-date picker, and react-tagsinput, react-select, react-video.',
            'Extensive experience with Promises to make asynchronous calls and use fetch API as an interface to fetch resources.',
            'Experience with JavaScript (ES5/ES6/ES7) - Closures, Hoisting, Strict Mode, Scope, Block Scoping, Promises, Generators, Maps and Sets, String interpolation, async and await, array Extensions, modules, and classes.',
            'Built out Restful endpoints and lightweight aggregation layers using NodeJs frameworks such as Express, Body parser, cluster, process, Winston, Redis, passport, mongoose, lodash, etc.',
            'Used Mongoose Schema/Model to create, update and delete with Express controllers.',
            'Created Restful APIs with Express and used MongoDB for persistence and Redis for caching.',
            'Created SPA (Single Page Application) by configuring React-Router. Used Browser Router for Web.',
        ]
    },

    {   id: 444,
        company: 'Bank of Arizona Phoenix',
        title: 'front-end developer',
        time: 'Sep 2015 - Jun 2016',
        list: [
            'Worked with React props, state, keys, refs, events, default props, and propTypes.',
            'Experience with Redux for state management. Created store, actions, and reducers as pure functions.',
            'Experience with Redux middleware’s - react-video, react-select, react-tagsinput, react-datagrid, react-panels, react-calendar.',
            'Experience with third-party React components library like react-grid, react-sortable, react-tags, react-infinite-scroll, react-date picker, and react-tagsinput, react-select, react-video.',
            'Extensive experience with Promises to make asynchronous calls and use fetch API as an interface to fetch resources.',
            'Experience with JavaScript (ES5/ES6/ES7) - Closures, Hoisting, Strict Mode, Scope, Block Scoping, Promises, Generators, Maps and Sets, String interpolation, async and await, array Extensions, modules, and classes.',
            'Built out Restful endpoints and lightweight aggregation layers using NodeJs frameworks such as Express, Body parser, cluster, process, Winston, Redis, passport, mongoose, lodash, etc.',
            'Used Mongoose Schema/Model to create, update and delete with Express controllers.',
            'Created Restful APIs with Express and used MongoDB for persistence and Redis for caching.',
            'Created SPA (Single Page Application) by configuring React-Router. Used Browser Router for Web.',
        ]
    },
]